auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            PeterYuu.com
url:              http://peteryuu.com
feed:             /atom.xml
author:
    name:         PeterYuu
description:      "PeterYuu\'s Blog"
author_info:      <a href="http://peteryuu.com/about">PeterYuu</a>

copyright:
    - Design by <a href="http://peteryuu.com/about" title="PeterYuu" target="_blank">PeterYuu</a> &copy; 2013
